### ISSUE TITLE
Please build ipk

### ISSUE THREAD

**Issue by kevindoni** [koshev-msk/luci-app-mmconfig#1]
not support e3372h 607 hilink

**Comment by koshev-msk** [comment]
Thank for your issue! luci-app-mmconfig support only QMI modem, Hilink modem doest not.

**Comment by xan500** [comment]
Stopped switching in MBIM mode to OPENWRT 21.02.0 and higher, works only in QMI mode
On OPENWRT 19.07 everything was fine ...
